example.property: "I AM IN THE PROD ON GITHUB"
spring:
  datasource:
    url: jdbc:mysql://database:3306/msa-prod
    username: jayden
    password: "{cipher}ac045bc4d8ff2bcf88a55ff0894f27da2fd1573c40a08e0b080b42ba35129474"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: "true"
        show_sql: "true"
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
